apiVersion: v1
kind: Service
metadata:
  name: hermes-go-jumpserver
  namespace: ${K8S_NAMESPACE}
  labels:
    app: hermes-go-jumpserver
spec:
  selector:
    app: hermes-go-jumpserver
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
